### Authentication API - POST Request with Basic Authentication ###

POST http://localhost:your_port_number/authenticate
Authorization: Basic dGVzdEBzdW5iYXNlZGF0YS5jb206VGVzdEAxMjM=
Content-Type: application/json

{
  "login_id": "test@sunbasedata.com",
  "password": "Test@123"
}
